package com.bank.ooad.models.enums;

public enum TransactionStatus {
    IDLE, VALIDATING_INPUT, CHECK_DAILY_LIMIT, VERIFY_BALANCE, ANALYZE_RISK, INITIATING_DB_TXN, DEBITING, CREDITING, GENERATING_RECEIPT, ROLLBACK, REJECTED, COMPLETED
}
